apiVersion: v1
kind: Service
metadata:
  name: fp-example
  labels:
    app: fp-example
  namespace: fp
spec:
  type: ClusterIP
  selector:
    app: fp-example
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: fp-example
  namespace: fp
spec:
  tls:
    - hosts:
        - fp-example.app.durstexpress.eu
      secretName: ingress-delivery-web
  rules:
    - host: fp-example.app.durstexpress.eu
      http:
        paths:
          - path: /
            backend:
              serviceName: fp-example
              servicePort: 3000
